### ISSUE TITLE
Known Issue for which u provided solution to change line no 190 code

### ISSUE THREAD

**Issue by sachdevaankur90** [ncb000gt/ncb000gt.github.com#1]
So the problem has still persisted even if i have done the suggested change in ga.js file at line number 190.
I am pasting the error stack that i get after changing the code as suggested.

Following is the link to screenshot of my error stack.
"https://cloud.githubusercontent.com/assets/13054231/8363433/801d6612-1b9c-11e5-850b-d5dec1a0d6cb.png"

And the text form of error stack is below : 

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at GA.emit (events.js:74:15)
    at IncomingMessage.<anonymous> (E:\instalively-staging\node_modules\googlean
alytics\lib\ga.js:91:26)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)

Please look into it. And provide with a solution asap. 
![capture](https://cloud.githubusercontent.com/assets/13054231/8363546/321d64d4-1b9d-11e5-80e1-42ebf3c41d6c.PNG)

**Comment by sachdevaankur90** [comment]
@ncb000gt Please look into the issue
